version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE=http://localhost:8000
    restart: always
    network_mode: "host"
    env_file:
      - .env.local
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
